---
title: "Regresión"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: cerulean
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(wooldridge)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(gridExtra)
library(jtools)

data("wage1")
modelo1=lm(lwage~educ+exper+tenure, data=wage1)
modelo2=lm(wage~educ+exper+tenure, data=wage1)

```

Regresión_1
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Regresión LWage

```{r}


summ(modelo1, digits = 3)
```

###  Regresión Wage

```{r}


summ(modelo2, digits = 3)


```


Column {data-width=650}
-----------------------------------------------------------------------

### Regresion con Wage y Regresión con Log Wage

```{r}


plot_summs(modelo1, modelo2, scale = TRUE, plot.distributions = TRUE,legend.title =c( "Lwage","Wage"))


```


###  Wage y Log Wage

```{r}

library(ggplot2)
library(plotly)

a=ggplot(data = wage1) +
  geom_density(aes(x = wage), fill="red" )+ labs(x = "Wage", subtitle = "Sin trasnformar")
b=ggplot(data = wage1) +
  geom_density(aes(x = lwage), fill ="green")+ labs(x = "Log Wage", subtitle = "Transformación")
pla=ggplotly(a)
plb=ggplotly(b)
subplot(pla,plb)

```



Regresión_2
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------


### LWage vs Educación

```{r}



library(ggplot2)
library(plotly)
a= ggplot(wage1, aes(x=educ, y=lwage)) + 
  geom_point(shape=18, color="blue")+
  geom_smooth(method=lm, se=FALSE, linetype="dashed",
             color="darkred")


ggplotly(a)

```


### Wage vs Educación

```{r}



library(ggplot2)
library(plotly)
a= ggplot(wage1, aes(x=educ, y=wage)) + 
  geom_point(shape=18, color="blue")+
  geom_smooth(method=lm, se=FALSE, linetype="dashed",
             color="darkred")


ggplotly(a)

```

Column {data-width=650}
-----------------------------------------------------------------------


### Residuos con LWage

```{r}

tmp <- dplyr::select(wage1,lwage,educ) %>%dplyr::mutate(fits=fitted(modelo1),
                resids=resid(modelo1),
                sresids=rstudent(modelo1))
a=ggplot(data=tmp,mapping=aes(x=fits,y=resids)) +
  geom_point() +
  geom_hline(yintercept=0,linetype="dashed")+
  geom_smooth()
ggplotly(a)
```


### Residuos con Wage

```{r}

tmp <- dplyr::select(wage1,wage,educ) %>%dplyr::mutate(fits=fitted(modelo2),
                resids=resid(modelo2),
                sresids=rstudent(modelo2))
a=ggplot(data=tmp,mapping=aes(x=fits,y=resids)) +
  geom_point() +
  geom_hline(yintercept=0,linetype="dashed")+
  geom_smooth()
ggplotly(a)
```

