
# Teaching




### Universidad Externado (2016-Currently)

*   Bachelor in Data Science (Mathematics Department)

    + Intro Data Science
    + Bayesian Statistics
    
*   Master in Business Administration (Management Faculty)

    + Data Science   
    
*   Master in Business Administration (Law Faculty)

    + Data Science for Smart Cities  
    
*   Master in Project Investment (Management Faculty)
    
    + Stochastic Calculus
    
*   Finance, Goverment and International Affairs (Figri)

    + Econometrics
    + Quantitive Methodology
    + Statistics
    + Machine Learning
    + Data Science
  
    
### Universidad de La Salle (2019-2020)

*  Bachelor in Finance and International Trade
   + Derivatives
   + Risk Management
   + Econometrics
   + Capital Markets
   
    
### Universidad Central(2014-2019)

* Bachelor in Economics
  + Financial Mathematics
  + Derivatives
  + Computational Finance
* Bachelor in Mathematics
  + Computational Finance
  + Financial Stochastic Mathematics
  
### Universidad Jorge Tadeo Lozano (2016-2017)

* Bachelor in Finance and International Trade
  + Finance Theory
  




