---
title: "Variables adicionales"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(wooldridge)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(gridExtra)
library(jtools)
library(ggplot2)#
library(plotly)
library(lmtest)
library(forecast)
library(car)

data("wage1")
modelo1=lm(lwage~educ+exper+tenure+female+female*exper+ expersq, data=wage1)
modelo2=lm(lwage~educ+exper+tenure+ expersq, data=wage1)

```

Variables dicotómicas y variables al cuadrado
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Regresión LWage

```{r}
summ(modelo1, digits = 3)
```

###  Regresión Wage

```{r}


tmp <- dplyr::select(wage1,lwage,educ) %>%dplyr::mutate(fits=fitted(modelo1),
                resids=resid(modelo1),
                sresids=rstudent(modelo1))
a=ggAcf(tmp$resids) +ggtitle("Autocorrelación Residuos")
ggplotly(a)


```


Column {data-width=650}
-----------------------------------------------------------------------

### Regresion con Wage y Regresión con Log Wage

```{r}

x=0:13
fy=modelo1$coefficients[1]+modelo1$coefficients[5]+modelo1$coefficients[2]*x+(modelo1$coefficients[3]+modelo1$coefficients[7])*x+modelo1$coefficients[4]*x+modelo1$coefficients[6]*x^2
My=modelo1$coefficients[1]+modelo1$coefficients[2]*x+modelo1$coefficients[3]*x+modelo1$coefficients[4]*x+modelo1$coefficients[6]*x^2

df=data.frame(cbind(x,fy,My))
colnames(df)=c("Tiempo","Mujeres","Hombres")

library(ggplot2)
library(plotly)

a=ggplot(data = df) +
  geom_line(aes(x = Tiempo,y=Mujeres), color="red" )+ labs(x = "Tiempo", y="Cambio en el salario", title = "Brecha Salarial por Género")+
  geom_line(aes(x = Tiempo,y=Hombres), color="blue" )+ labs(x = "Tiempo", y="Cambio en el salario")
  
ggplotly(a)



```


###  Cambios Marginales

```{r}

x=0:30

exp2=modelo1$coefficients[1]+modelo1$coefficients[3]*x+modelo1$coefficients[6]*x^2

df=data.frame(cbind(x,exp2))
colnames(df)=c("Experiencia","DeltaSalario")

library(ggplot2)
library(plotly)

a=ggplot(data = df) +
  geom_line(aes(x = Experiencia,y=DeltaSalario), color="red" )+ labs(x = "Experiencia", y="Cambio en el salario", title = "Cambios Marginales")
  
ggplotly(a)



```



Heterocedasticidad
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------


### Errores2 vs educ

```{r}

residuos2=resid(modelo1)^2

df1=data.frame(residuos2,wage1$educ,wage1$exper,wage1$tenure)
colnames(df1)=c("residuos1","educ","exper","tenure")
library(ggplot2)
library(plotly)
a= ggplot(df1, aes(x=educ, y=residuos2)) + 
  geom_point(shape=18, color="blue")+
  geom_smooth(method=lm, se=FALSE, linetype="dashed",
             color="darkred")


ggplotly(a)

```


### Errores2 vs exper

```{r}



residuos2=resid(modelo1)^2

df1=data.frame(residuos2,wage1$educ,wage1$exper,wage1$tenure)
colnames(df1)=c("residuos1","educ","exper","tenure")
library(ggplot2)
library(plotly)
a= ggplot(df1, aes(x=exper, y=residuos2)) + 
  geom_point(shape=18, color="blue")+
  geom_smooth(method=lm, se=FALSE, linetype="dashed",
             color="darkred")


ggplotly(a)

```

Column {data-width=650}
-----------------------------------------------------------------------


### Errores2 vs tenure

```{r}

residuos2=resid(modelo1)^2
ajustados=fitted(modelo1)

df1=data.frame(residuos2,wage1$educ,wage1$exper,wage1$tenure)
colnames(df1)=c("residuos1","educ","exper","tenure")
library(ggplot2)
library(plotly)
a= ggplot(df1, aes(x=tenure, y=residuos2)) + 
  geom_point(shape=18, color="blue")+
  geom_smooth(method=lm, se=FALSE, linetype="dashed",
             color="darkred")


ggplotly(a)

```


### Tests sobre los residuos

```{r}
residuos=resid(modelo1)
residuos2=resid(modelo1)^2
ajustados=fitted(modelo1)

df1=data.frame(residuos,residuos2,wage1$educ,wage1$exper,wage1$tenure,ajustados)
colnames(df1)=c("residuos","residuos2","educ","exper","tenure","ajustados")
library(ggplot2)
library(plotly)
a= ggplot(df1, aes(x=ajustados, y=residuos2)) + 
  geom_point(shape=18, color="blue")+
  geom_smooth(method=lm, se=FALSE, linetype="dashed",
             color="darkred")


ggplotly(a)

```

Inferencia 
=======================================================================


Column {data-width=650}
-------------------------

### Inferencia Heterocedasticidad y Normalidad

```{r}


residuos=resid(modelo1)
bptest(modelo1)### Prueba de heterocedasticidad
ks.test(residuos,"pnorm") ### Test de normalidad

```

### QQ plot residuales


```{r}

a= ggplot(df1, aes(sample=residuos),color="red") + 
  geom_qq( )+stat_qq() +
  stat_qq_line()


ggplotly(a)

```

Column {data-width=650}
-------------------------

### Densidad

```{r}

library(ggplot2)
library(plotly)

a=ggplot(data = df1) +
  geom_density(aes(x = residuos), fill="red" )+ labs(x = "Residuos", subtitle = "Distribución de los residuales")
ggplotly(a)


```



